### ISSUE TITLE
PlayerShooting.csが変更されてない

### ISSUE THREAD

**Issue by JunichiroHashimoto** [tspringk/SurvivalShooterExtended#3]
たぶんPlayerShooting.csの変更が反映されてなくて
InputManager.cs InvokePlayerFireに何も登録されない状態になってます

**Comment by tspringk** [comment]
失礼しました。前回講義で、ある質問を受けて、一時的にイベントデリゲート関連のコードをコメントアウトしたままでした。
Develop/fix-playershooting ブランチを作成し、コードを元にもどしました。
自作自演プルリク、コードレビュー、マージ済みです（笑）
https://github.com/tspringk/SurvivalShooterExtended/pull/5

ただ、敵キャラが倒れませんね。。もともとこういう状態だったでしょうか？

**Comment by JunichiroHashimoto** [comment]
敵キャラ倒せてたと思いますよ
レイヤー設定が消えてるかも
今床レイヤーの追加の修正をプッシュしましたが
Enemyレイヤーとかあったのでは

**Comment by tspringk** [comment]
あー、なるほど、そうかもしれません。
一眠りして、仕事の合間に確認してみます
遅くにすみません！
